spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost/postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      default_schema: public
    database: postgresql
  main: 
    allow-bean-definition-overriding: true
server:
  port: 8090